# Generated by Django 4.2 on 2026-02-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='hot100_order',
            field=models.PositiveIntegerField(db_index=True, default=9999, verbose_name='Hot100 顺序'),
        ),
        migrations.AlterModelOptions(
            name='problem',
            options={
                'ordering': ['hot100_order', 'number'],
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
            },
        ),
    ]
