# Generated by Django 4.2.28 on 2026-02-18 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(verbose_name='提交代码')),
                ('time_spent', models.IntegerField(verbose_name='用时(秒)')),
                ('is_passed', models.BooleanField(default=False, verbose_name='是否通过')),
                ('test_cases_total', models.IntegerField(default=0, verbose_name='总测试用例')),
                ('test_cases_passed', models.IntegerField(default=0, verbose_name='通过用例数')),
                ('feedback', models.TextField(blank=True, verbose_name='反馈/优化建议')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='problems.problem', verbose_name='题目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='users.profile', verbose_name='用户')),
            ],
            options={
                'verbose_name': '提交记录',
                'verbose_name_plural': '提交记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
