# Generated by Django 4.2 on 2026-02-19

from django.db import migrations, models


def seed_ai_prompts(apps, schema_editor):
    AIReviewPrompt = apps.get_model('submissions', 'AIReviewPrompt')

    default_items = [
        (
            'passed',
            (
                '你是资深算法面试官。用户这次提交已经通过。请只给“可执行的优化建议”，'
                '重点关注：时间复杂度、空间复杂度、边界条件、代码可读性。'
                '输出要求：先给一句总体评价；再给 3 条以内优化建议（每条包含“为什么 + 如何改”）；'
                '如果当前实现已接近最优，请明确说明并补充 1 条微优化建议。'
            ),
        ),
        (
            'failed',
            (
                '你是资深算法面试官。用户这次提交未通过。请根据题目信息与通过情况定位错误原因，'
                '给出可执行修复方案。输出要求：先指出最可能的核心错误（1-2 条）；'
                '再给修复步骤（按先后顺序）；最后给 2-3 个针对性测试用例用于自测。'
            ),
        ),
    ]

    for result_type, prompt in default_items:
        AIReviewPrompt.objects.update_or_create(
            result_type=result_type,
            defaults={'prompt': prompt},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='ai_feedback',
            field=models.TextField(blank=True, verbose_name='AI 反馈'),
        ),
        migrations.CreateModel(
            name='AIReviewPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_type', models.CharField(choices=[('passed', '通过后优化建议'), ('failed', '未通过纠错建议')], max_length=10, unique=True, verbose_name='提交结果类型')),
                ('prompt', models.TextField(verbose_name='提示词模板')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI 评估提示词',
                'verbose_name_plural': 'AI 评估提示词',
            },
        ),
        migrations.RunPython(seed_ai_prompts, migrations.RunPython.noop),
    ]
