# Generated by Django 4.2 on 2026-02-19

from django.db import migrations, models


def seed_ai_provider_config(apps, schema_editor):
    AIProviderConfig = apps.get_model('submissions', 'AIProviderConfig')

    if AIProviderConfig.objects.exists():
        return

    AIProviderConfig.objects.create(
        provider_name='modelverse-openai-compatible',
        api_base_url='https://api.modelverse.cn/v1',
        api_key='',
        model_name='gpt-5.1-codex-mini',
        timeout_seconds=45,
        is_active=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_submission_ai_prompt_and_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(default='modelverse-openai-compatible', max_length=100, verbose_name='提供方名称')),
                ('api_base_url', models.URLField(default='https://api.modelverse.cn/v1', verbose_name='API Base URL')),
                ('api_key', models.TextField(blank=True, verbose_name='API Key（明文）')),
                ('model_name', models.CharField(default='gpt-5.1-codex-mini', max_length=100, verbose_name='模型名称')),
                ('timeout_seconds', models.PositiveIntegerField(default=45, verbose_name='超时秒数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI Provider 配置',
                'verbose_name_plural': 'AI Provider 配置',
            },
        ),
        migrations.RunPython(seed_ai_provider_config, migrations.RunPython.noop),
    ]
