# Generated by Django 4.2 on 2026-03-04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_dueltimerstate_elapsed_and_running_since'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuelRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=4, unique=True, verbose_name='房间号(4位)')),
                ('status', models.CharField(choices=[('waiting', '等待加入'), ('active', '进行中'), ('finished', '已完成')], default='waiting', max_length=20, verbose_name='房间状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duel_rooms', to='problems.problem', verbose_name='题目')),
                ('user_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duel_rooms_as_a', to='users.profile', verbose_name='用户A(创建者)')),
                ('user_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duel_rooms_as_b', to='users.profile', verbose_name='用户B(加入者)')),
            ],
            options={
                'verbose_name': '对战房间',
                'verbose_name_plural': '对战房间',
            },
        ),
    ]
